### ISSUE TITLE
Error in running training pipeline

### ISSUE THREAD

**Issue by jetiba-ms** [Azure-Samples/MLOpsDatabricks#26]
During the "Train model using AML with Remote Compute" in the Azure Devops pipeline, it is returned an error: "AML Pipelne failed". 
I investigated the failure in the Databricks cluster, the step **DBPythonInLocalMachine** fails and in the Spark Drivers Logs there is the following error:

```
Fri Sep 27 15:09:25 2019 py4j imported
Fri Sep 27 15:09:26 2019 Python shell started with PID  2714  and guid  f151b88db8af47e791fa34e2b0ec62ea
Fri Sep 27 15:09:26 2019 Python shell executor start
Fri Sep 27 15:09:28 2019 py4j imported
Fri Sep 27 15:09:29 2019 Python shell started with PID  2728  and guid  0d38bc7015fe4ad4ba3e88972053fdac
Fri Sep 27 15:09:29 2019 Python shell executor start
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<command--1> in <module>()
     13 
     14 with open(filename, "rb") as f:
---> 15   exec(f.read())
     16 

<string> in <module>()

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

I didn't change anything in the code, just the environment variables.

Do you have any hint to solve this issue?

**Comment by heikofriedrich** [comment]
Hi,

did you solve the problem?
I had  a similar the problem that environment variables are not passed to the python script environment if you don't explicitly mention them in the piepeline task under "env: ", not all environment variables that need to be passed to the python script are listed in the task. That's why i got an error here.

**Comment by jetiba-ms** [comment]
Hi @heikofriedrich
I have tried to add variables as you describe, but it returns the same error.
Any help on that will be really appreciated.

**Comment by heikofriedrich** [comment]
Hi @jetiba-ms 

I ran in the same error as you now. Problem was the code src/train/train.py line 49. If no argument for NUM_EPOCHS is passed this fails. so i changed the code in line 46 to 

```
if ARGS.MODEL_PATH == "" **or ARGS.NUM_EPOCHS is None**:
    NUM_EPOCHS = 5
```

this works for me now and the pipeline runs through

**Comment by jetiba-ms** [comment]
Changing that line of code it works.
Thanks a lot.
